# Generated by Django 4.1.7 on 2023-05-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='course_code',
            new_name='course',
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='internal.student'),
            preserve_default=False,
        ),
    ]
