# Generated by Django 4.1.7 on 2023-05-07 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_rename_course_code_mark_course_mark_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.course')),
                ('staff_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='staff_ID',
            field=models.ManyToManyField(through='internal.CourseMapping', to=settings.AUTH_USER_MODEL),
        ),
    ]
