# Generated by Django 4.1.7 on 2023-05-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
